workload = {
    # 0: {  
    #     "operator_type": "Conv",
    #     "equation": "O[t][b][k][oy][ox]+=W[k][c][fy][fx]*I[t][b][c][iy][ix]",
    #     "dimension_relations": ["ix=2*ox+1*fx", "iy=2*oy+1*fy"],
    #     "loop_dim_size": {
    #         "B": 1,
    #         "K": 32,
    #         "C": 6,
    #         "OY": 180,
    #         "OX": 320,
    #         "FY": 3,
    #         "FX": 3,
    #         "T": 8,
    #     },
    #     "operand_precision": {"O": 16, "O_final": 4, "W": 4, "I": 4},
    #     "operand_source": {"W": [], "I": []},
    #     "constant_operands": ["I", "W"],
    #     "weight_operand": "W",
    #     'memory_operand_links': {'O': 'O', 'I': 'I1', 'W': 'I2'},
    #     "input_path": 'max_0.npy',
    #     "time_operand": "T",

    # },    
       16: {  
        "operator_type": "Conv",
        "equation": "O[b][t][k][oy][ox]+=W[k][c][fy][fx]*I[b][t][c][iy][ix]",
        "dimension_relations": ["ix=ox+2*fx", "iy=oy+2*fy"],
        "loop_dim_size": {
            "B": 1,
            "K": 256,
            "C": 256,
            "OY": 5,
            "OX": 3,
            "FY": 3,
            "FX": 3,
            "T": 8,
            #"C": "16"
        },
        "operand_precision": {"V": 8, "O": 1, "W": 4, "I": 1},
        #"operand_precision": {"O_final": 8, "O": 16, "W": 8, "I": 8},
        "operand_source": {"W": [], "I": []},
        "state_operand": "V",
        "time_operand": "T",
        "constant_operands": ["W", "I"],
        "state": True,
        #"sparse": False,
        #"i_rate": 0.05,
        'memory_operand_links': {'O': 'O', 'I': 'I1', 'W': 'I2', 'V': 'S'},
        #"input_path": 'max_11.npy',
        #"coarse_sparse": False,

    },     
}